"""
Unit tests for design token generators (no design engine / CSV required).
"""
import json
import sys
import tempfile
import unittest
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from tokens import (  # noqa: E402
    DEFAULT_TOKENS,
    STYLE_TOKEN_DEFAULTS,
    to_css_variables,
    to_json_summary,
    to_tailwind_config,
    to_w3c_tokens,
    write_token_files,
)


def _fake_design_system() -> dict:
    return {
        "project_name": "Serenity Spa",
        "category": "Wellness",
        "pattern": {
            "name": "Hero-Centric + Social Proof",
            "sections": "Hero > Features > CTA",
            "cta_placement": "Above fold",
            "color_strategy": "",
            "conversion": "Trust",
        },
        "style": {
            "name": "Soft UI Evolution",
            "type": "General",
            "effects": "Soft depth",
            "keywords": "soft",
            "best_for": "apps",
            "performance": "Good",
            "accessibility": "AA+",
            "light_mode": "yes",
            "dark_mode": "yes",
        },
        "colors": {
            "primary": "#E8B4B8",
            "on_primary": "#1a1a1a",
            "secondary": "#A8D5BA",
            "accent": "#C9A961",
            "background": "#FFFBF7",
            "foreground": "#2D2A32",
            "muted": "rgba(0,0,0,0.45)",
            "border": "rgba(0,0,0,0.12)",
            "cta": "#C9A961",
            "text": "#2D2A32",
        },
        "typography": {
            "heading": "Cormorant Garamond",
            "body": "Montserrat",
            "mood": "calm",
            "best_for": "spa",
            "google_fonts_url": "",
            "css_import": "",
        },
        "key_effects": "soft transitions",
        "anti_patterns": "harsh neons + tiny tap targets + busy hero",
        "decision_rules": {},
        "severity": "MEDIUM",
    }


class TestTokens(unittest.TestCase):
    def test_style_defaults_table_has_minimum_entries(self):
        n = len(STYLE_TOKEN_DEFAULTS)
        # Spec: 5 named examples + at least 12 more (>= 17)
        self.assertGreaterEqual(n, 17)
        for k in (
            "Brutalism",
            "Soft UI Evolution",
            "Neumorphism",
            "Glassmorphism",
            "Minimalism & Swiss Style",
        ):
            self.assertIn(k, STYLE_TOKEN_DEFAULTS, f"missing required style: {k}")

    def test_default_tokens_keys(self):
        for key in (
            "radius_sm",
            "radius_md",
            "radius_lg",
            "shadow_sm",
            "shadow_md",
            "transition_fast",
            "transition_base",
        ):
            self.assertIn(key, DEFAULT_TOKENS)

    def test_to_css_variables_shape(self):
        css = to_css_variables(_fake_design_system())
        self.assertIn(":root {", css)
        for need in (
            "--color-primary",
            "--color-secondary",
            "--color-cta",
            "--color-background",
            "--color-text",
            "--color-border",
            "--color-muted",
            "--font-heading",
            "--font-body",
            "--radius-sm",
            "--radius-md",
            "--radius-lg",
            "--shadow-sm",
            "--shadow-md",
            "--transition-fast",
            "--transition-base",
        ):
            self.assertIn(need, css)
        for n in "12345678":
            self.assertIn(f"--space-{n}:", css)

    def test_to_tailwind_config_shape(self):
        tw = to_tailwind_config(_fake_design_system())
        self.assertTrue(tw.startswith("/** @type {import('tailwindcss').Config} */"))
        self.assertIn("theme:", tw)
        self.assertIn("extend:", tw)
        self.assertIn("colors:", tw)
        self.assertIn("fontFamily:", tw)
        self.assertIn("borderRadius:", tw)
        self.assertIn("boxShadow:", tw)
        self.assertIn("primary:", tw)
        self.assertIn("Generated by UI UX Pro Max for project: Serenity Spa", tw)

    def test_to_w3c_tokens_shape(self):
        w3c = to_w3c_tokens(_fake_design_system())
        self.assertEqual(
            w3c.get("$schema"),
            "https://design-tokens.github.io/community-group/format/",
        )
        self.assertIn("color", w3c)
        self.assertEqual(w3c["color"]["primary"]["$type"], "color")
        self.assertIn("$value", w3c["color"]["primary"])
        self.assertIn("font", w3c)
        self.assertEqual(w3c["font"]["heading"]["$type"], "fontFamily")
        self.assertIn("radius", w3c)
        self.assertIn("shadow", w3c)
        self.assertIn("space", w3c)
        for k in "12345678":
            self.assertIn(k, w3c["space"])

    def test_to_json_summary_shape(self):
        s = to_json_summary(_fake_design_system())
        self.assertEqual(s["project"], "Serenity Spa")
        self.assertEqual(s["style"], "Soft UI Evolution")
        self.assertEqual(s["pattern"], "Hero-Centric + Social Proof")
        self.assertIn("generated_at", s)
        self.assertIn("colors", s)
        self.assertEqual(s["typography"]["heading"], "Cormorant Garamond")
        self.assertIsInstance(s["anti_patterns"], list)
        self.assertTrue(len(s["anti_patterns"]) >= 1)
        self.assertIsInstance(s["checklist"], list)
        self.assertTrue(len(s["checklist"]) >= 5)

    def test_write_token_files_creates_four_nonempty(self):
        ds = _fake_design_system()
        with tempfile.TemporaryDirectory() as tmp:
            got = write_token_files(ds, tmp)
            self.assertEqual(len(got), 4)
            names = {Path(p).name for p in got}
            self.assertSetEqual(
                names,
                {
                    "tokens.css",
                    "tailwind.config.tokens.js",
                    "tokens.json",
                    "design-system.json",
                },
            )
            for p in got:
                self.assertTrue(Path(p).is_file(), p)
                self.assertGreater(Path(p).stat().st_size, 0, p)
            with open(Path(tmp) / "design-system.json", encoding="utf-8") as f:
                j = json.load(f)
            self.assertEqual(j["project"], "Serenity Spa")


if __name__ == "__main__":
    unittest.main()
